version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "file_storage"
      IP_SERVER: "45.82.68.203"
      PORT_SERVER: 10099

    volumes:
      - ./:/main
    ports:
      - "10099:10099"
    network_mode: "host"
