version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "tyre_app"
      IP_SERVER: "167.235.253.89"
      PORT_SERVER: 10090
      PROTOCOL: "http"

    volumes:
      - ./:/main
#    ports:
#      - "10090:10090"
    network_mode: "host"
